config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  post 'zipcode' => 'home#zipcode'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home Controller
class HomeController < ApplicationController
  def index; end

  def zipcode
    @zipcode_query = params[:zipcode]
    @url = "http://api.weatherapi.com/v1/current.json?key=80ece6c16a9d42b58b1112152212211&q=#{@zipcode_query}"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    if @output['error'] || @zipcode_query == ''
    elsif @output['location']['country'] == 'UK'
      @final_output = @output['current']['temp_c']
      @final_output_location = @output['location']['name']
      @final_temperature_status = temperature_check(@final_output)
    end
  end

  private

  def temperature_check(temp)
    if temp > 27
      'Hot'
    elsif temp > 17 && temp < 27
      'Warm'
    else
      'Cold'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Home Helper
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Potcode Weather Search</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
      <%= form_tag zipcode_path, :method => 'POST' do %>
      <div class="d-flex">
        <%= text_field_tag 'zipcode', nil, placeholder: 'Seach Postcode', class: "d-flex" %>
        <%= submit_tag 'Search', class: "btn btn-outline-secondary" %>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= @final_output %>

app/views/home/zipcode.html.erb
<% if !@final_output_location %>
  <h2>Error, invalid postcode</h2>
<% else %>
  <h2> The Temperature for <%= @final_output_location %> is currently <%= @final_output %>°C</h2>
  <h1>It is <%= @final_temperature_status %></h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      </br>
      <%= yield %>
    </div>
  </body>
</html>